### ISSUE TITLE
Solace multiple consumers issue

### ISSUE THREAD

**Issue by IagoSchlisting** [SolaceProducts/solace-spring-cloud#196]
Hello,

During my tests, I have encountered a weird situation:

I've pre-filled my queue with lots of messages. Then, I started my spring cloud stream application to consume that queue, with `.concurrency=50`. Only a few threads/consumers processed the messages. Somehow, the messages that were in the queue are not being distributed among all consumers, but when publishing messages to this queue when my application is already started, all consumers process as expected. 

My queue is not exclusive, not anonymous and neither uses polled consumers, also all consumers seem to be connected when my application starts. Any idea why this happens? Is this an expected behavior?

I'm looking forward to your return.
Regards,

**Comment by Nephery** [comment]
> I've pre-filled my queue with lots of messages.

Try starting your application first, then filling your queue. Consumers are started sequentially, meaning that messages could be funneled to the consumers which start earlier if your test is using a pre-filled queue.

**Comment by IagoSchlisting** [comment]
> Hi @IagoSchlisting, Can you confirm that you are setting `spring.cloud.stream.bindings.<bindingName>.consumer.concurrency` ?

@Mrc0113 Yes, I'm using scs concurrency configuration.

> Also I'm going to move this to the `solace-spring-cloud` project since that is where the Cloud Stream binder resides.

Ok thank you!

**Comment by IagoSchlisting** [comment]
> > I've pre-filled my queue with lots of messages.
> 
> Try starting your application first, then filling your queue. Consumers are started sequentially, meaning that messages could be funneled to the consumers which start earlier if your test is using a pre-filled queue.

@Nephery filling the queue after starting application works good, so is this expected? I ask because for the same scenario using scs-rabbit it distributes fine among all consumers.

**Comment by Nephery** [comment]
Yes, this is expected.

If you had enough messages in your pre-filled queue, then once all consumers have started up, you should notice that message distribution will _eventually_ reach a steady-state and use all the consumers.
