### ISSUE TITLE
[SOL-43137] Cloud Stream Binder Consider support for Batch Consumers

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-cloud#22]
[Enhancement for Consideration] 
Consider extending the solace cloud stream binder to allow for the use of the framework's definition of [Batch Consumers](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/current/reference/html/spring-cloud-stream.html#_batch_consumers). 

This would be useful if a developer wants to operate across many events at once. Example if I am receiving 100msg/s and need to persist to the DB I probably want to make 1 insert for all 100 messages instead of 100 separate inserts.

**Comment by Mrc0113** [comment]
If we decide to implement this the Rabbit binder would be a good reference point.

**Comment by Mrc0113** [comment]
Just a note that when we eventually add this feature we should consider adding the ability to more easily configure the  setting of the "JCSMPProperties.PUB_ACK_WINDOW_SIZE" (via solace-spring-boot?) or at a minimum provide guidance in docs that you'd probably want to up that from the default of 1.

**Comment by Mrc0113** [comment]
Hi @jmosmg, 
It's on our radar but we haven't committed to what release it will be in yet. Can you share more around your use case? 
Note that we recently released the ability to use [manual/client acknowledgements](https://github.com/SolaceProducts/solace-spring-cloud/tree/master/solace-spring-cloud-starters/solace-spring-cloud-stream-starter#manual-message-acknowledgment) which would allow you to do "manual batch" since you can handle events in other threads....this would allow you to internally wait to have a batch of X messages before doing a bulk insert to a database and then acknowledging them afterwards as an example.  

If your use case requires privacy feel free to join the solace community and send me a private message over there: [https://solace.community/](https://solace.community/). My username is just "marc"

**Comment by jmosmg** [comment]
Hi Marc,

Thanks for the prompt response. We have tried this approach and it works for what we are trying to achieve. We are persisting messages into a database and trying out multiple approaches to improving the performance of the persistence, with one being a batch insert and acknowledgement once the full batch is inserted.

Thanks!
