### ISSUE TITLE
headerExclusions: for inbound messages

### ISSUE THREAD

**Issue by GreenRover** [SolaceProducts/solace-spring-cloud#235]
We currently face a problem with the headerExclusions options.

**The situation:**
Spring boot 2.7 application sends out messages with spring-cloud-stream
And will add unintentionally following header to messages.
nativeHeaders: a base 64 encoded thing
solace_scst_serializedHeaders: [nativeHeaders, id]

A spring boot 3.1.2 application wants to receive those messages via spring-cloud-stream
But spring-cloud-stream changed the model of the `nativeHeaders`
This leads to be not able to consume the message with the new application, without modifying the old data sender.

**The solution**
Add option `headerExclusions` for message consumer as well.

**Comment by Nephery** [comment]
Fixed with #235
