### ISSUE TITLE
[SOL-43239] Enhance destination Wildcard Handling in SCSt Binder

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-cloud#3]
Consider enhancing how the `destination` field is treated when wildcards are in being used. 
Maybe replace `>` or `*` with a different character that is valid in the queue name and apply the proper topic subscription to it

More info:
If I want to subscribe to `pub/sub/plus` I can do that successfully by specifying that as a `destination` in my bindings. However if I want to subscribe to `pub/sub/plus/>` I can no longer do that as `>` is not a valid character in a queue name. This forces me to specify a different destination name and then use the `spring.cloud.stream.solace.bindings.<function-in-0>.consumer.queueAdditionalSubscriptions` field to add the topic. This is inconvenient and can be confusing when ACLs come into play.

**Comment by Nephery** [comment]
We should replace `>` and `*` with `_`. We can make it configurable in the future if we need to.

**Comment by Nephery** [comment]
Closed with #75
