### ISSUE TITLE
[SOL-43234] Pulisher not handling failed async responses

### ISSUE THREAD

**Issue by Nephery** [SolaceProducts/solace-spring-cloud#34]
The binder's [producer's publisher event handler](https://github.com/SolaceProducts/solace-spring-cloud/blob/master/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/util/JCSMPSessionProducerManager.java#L30) does not handle async failed responses. Upon a failed publish response, it should at the very least send the message to the binder's error channel. This is currently what the binder and the SCSt framework does for any synchronous errors received during publishing.

Not entirely sure if waiting for the response should be a blocking action on the publisher or not. Probably not.

Looking at the [Guaranteed Delivery sample](https://solace.com/samples/solace-samples-java/confirmed-delivery/), it looks like we need to at least add the message itself as part of the message's correlation key. Also, the [publisherEventHandler](https://github.com/SolaceProducts/solace-spring-cloud/blob/1.1.1/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/util/JCSMPSessionProducerManager.java#L30) should be updated to use [JCSMPStreamingPublishCorrelatingEventHandler](https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/JCSMPStreamingPublishCorrelatingEventHandler.html#handleErrorEx(java.lang.Object,%20com.solacesystems.jcsmp.JCSMPException,%20long)) instead of the deprecated [JCSMPStreamingPublishEventHandler](https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/JCSMPStreamingPublishEventHandler.html).

To test this, you can set your ACL profile's `Publish Default Action` to `disallow` and then try to publish a message.

**Comment by Nephery** [comment]
> it looks like we need to at least add the message itself as part of the message's correlation key. 

Would this cause a message size issue? At a glance, it sounds like this might result in messages being twice as big than they normally should be. Maybe we should cache this in application memory instead? Though would that cause an application memory usage issue?

**Comment by Mrc0113** [comment]
@Nephery Looking at [this link](https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/JCSMPStreamingPublishCorrelatingEventHandler.html#handleErrorEx(java.lang.Object,%20com.solacesystems.jcsmp.JCSMPException,%20long)) it says: 
> Note: Direct messages are not buffered by the publishing API, and error responses from the appliance cannot be correlated to published Direct messages. As a result, when a Direct message is rejected by an error response, the key parameter to this callback is null.

Which to me means that the publishing API **is** buffering messages and I would imagine there should be a way to retrieve the message from the API via the returned key.

**Comment by Mrc0113** [comment]
Also I think we need specific error handling depending on the `JCSMPErrorResponseException`. For example if the message is too large then we won't be able to republish it to the error queue anyway, but if it was invalid topic syntax sending to an error queue might make more sense. There are other issues such as the MAX_MESSAGE_USAGE_EXCEEDED and SPOOL_OVER_QUOTA that a retry could make sense.  

![image](https://user-images.githubusercontent.com/1815312/98141939-33072a00-1e95-11eb-9170-06b8061bd525.png)

**Comment by Nephery** [comment]
> 
> 
> > it looks like we need to at least add the message itself as part of the message's correlation key.
> 
> Would this cause a message size issue? At a glance, it sounds like this might result in messages being twice as big than they normally should be. Maybe we should cache this in application memory instead? Though would that cause an application memory usage issue?

Discussed with @Mrc0113 . Apparently this is local to the API, and not an actual message property. So this is not really much of concern anymore aside from looking weird.

**Comment by GreenRover** [comment]
I created a first pull request for this issue: https://github.com/SolaceProducts/solace-spring-cloud/pull/61

**Comment by Nephery** [comment]
Closed with #75
