### ISSUE TITLE
[SOL-43463] Fix PR Build Failures and Migrate to Github Actions

### ISSUE THREAD

**Issue by Nephery** [SolaceProducts/solace-spring-cloud#52]
Due to the changes to Travis, we need to migrate to Github Actions.

As for PR build failures, unless we have a way to securely provide out test broker credentials to the tests, we should only run the unit tests for PR builds.

**Comment by Mrc0113** [comment]
@Nephery I think we can consider using the `testcontainers` project to stand up a broker for integration tests if you'd like to run them. 

Example of someone doing that here: https://github.com/spierepf/solace-junit5-test/blob/master/src/test/java/com/example/demo/CreateNewMessageVpnTests.java

Swen also mentioned it in the community here: https://solace.community/discussion/493/integration-functional-testing-with-junit-and-solace

**Comment by Nephery** [comment]
I haven't taken a deep look into `testcontainers` yet, but I heard this is compatible with Github Actions. So I agree that its something very worth looking into.

Also, something else we should do is test building against all versions of Java >=8 as to prevent issues like #38 moving forward.

**Comment by Nephery** [comment]
Closed with #75
