### ISSUE TITLE
support for concurrency parameter refresh on the fly 

### ISSUE THREAD

**Issue by anishkuti** [SolaceProducts/solace-spring-cloud#69]
support for concurrency parameter refresh on the fly  . It would have been better to have min & max-concurrency parameter and threads will be scaled up based on message load in the queue. Spring MDP used to give that support but can not find spring cloud stream

**Comment by Nephery** [comment]
The concurrency configuration is defined by the [spring-cloud-stream framework](https://github.com/spring-cloud/spring-cloud-stream), not this binder. I recommend opening an issue there.
