### ISSUE TITLE
Sending huge messages

### ISSUE THREAD

**Issue by GreenRover** [SolaceProducts/solace-spring-cloud#81]
Hello we habe following situation:
- Want send message over 400MB
- Solace have a per message limit for persistent messages of 30MB / for cloud broker 10MB

A possible solution for this problem is to:
- Chunk message on sender side.
- Send all messages with same correlationId
- Add header for chunk count and chink index
- Send all chunks in a single transaction 

Any idea ho this could be implemented with spring cloud stream?

What do you think about implementing this feature into this binder?

**Comment by GreenRover** [comment]
@Mrc0113 @Nephery  What do you think about this feature?

**Comment by helios57** [comment]
We would also vote for @GreenRover's solution.

Althoug it would be nice just to have the tools/interface to do it, maybe with a default implementation.

For example to be able provide a MessageSplitter and a MessageMerger.

`
public class MessageSplitter {
    Stream<PartialMessage> splitMessage(Message message){
        ...
    }
}

public class MessageMerger {
    Message splitMessage(Stream<PartialMessage> partialMessageStream){
        ...
    }
}
`

**Comment by adrianbader** [comment]
We would also be interessted in a solution since we currently upload too large payloads to S3 and send a presigned url to the S3 object as message payload.

**Comment by PhilippeKhalife** [comment]
@GreenRover for your use case, do you think the consumer and publisher are limited to being spring-cloud-streams apps?  Is there a need split up messages to be consumed by another consumer on another API?

**Comment by GreenRover** [comment]
@PhilippeKhalife For my use case only spring cloud stream apps are involved.

**Comment by Mrc0113** [comment]
Thanks for raising this feature request for discussion @GreenRover. And thank you @adrianbader and @helios57 for sharing that you'd be interested as well. 

You have probably thought about the different options for this, but just in case or for future folks that come across this there are usually 2 different choices to send large messages: 
1. Message Chunking (or Splitter + Aggregation) 
2. Claim Check Pattern (essentially store the message externally + provide how to get it in the message)

Obviously there are pros and cons of each option and your choice of which option to go with will differ based on requirements. You can do a quick google to get the details of each :) 

Just to be sure @helios57 & @adrianbader would you both be hoping for a simplified way to implement Option 1 like @GreenRover is explaining? 

Also a note for everyone (including myself later). The spring-cloud-stream-app-starters repo does have some sample apps that implement option 1 based off what Spring Integration provides. This is something we should look at when designing what support the binder might be able to provide, but also some apps that might prove useful for folks trying to implement this pattern prior to having binder support. Note that I have not personally used/run these samples before but figured I'd share :) 
* splitter: https://github.com/spring-cloud-stream-app-starters/splitter
* aggregator: https://github.com/spring-cloud-stream-app-starters/aggregator

**Comment by GreenRover** [comment]
@Mrc0113 Thanks for those code snippets.
But this will not work because we habe to send all parts im same transaction. This is why i asked to add this to the binder.
If it is general ok i can create a pull request , if there is a chance that you will accept it

**Comment by GreenRover** [comment]
Going now in direction partitioning.
