### ISSUE TITLE
[SOL-35673] Consider setting DMQ Eligible to true by default in SCSt. Binder v3.0

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-cloud#9]
Consider setting DMQ Eligible to true by default in v2.0. This is a solace best practice to decouple publishers & consumers and should be an _opinion_ in the style of spring boot.  

Note this would be an `enhancement`, but I can't label

**Comment by Nephery** [comment]
Is this a backwards-compatibility breaking change? If so, then I assume you meant to say v3.0?

**Comment by Mrc0113** [comment]
It's not actually backwards-compatibility breaking from a Spring Cloud Stream perspective, but if someone already had SCSt. apps running in their ecosystem that are publishing events consumed by other applications (not SCSt) and this change was made they _could_ now have more messages showing up on their DMQs that wouldn't have before.

So _if_ we are going to have a major version update soon due to the other open issues then I would include this with those in that release. And yes I meant v3.0 if that's next 😛

**Comment by Nephery** [comment]
Closed with #75
